version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: genai-backend
    ports:
      - "3333:3333" # Sesuaikan dengan port dari .env backend
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - redis_cache

  frontend:
    build:
      context: ./frontend
    container_name: genai-frontend
    ports:
      - "18888:80" # Map host port 18888 ke container port 80
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: unless-stopped
